exclude:
- less
- Gemfile
- Gemfile.lock
- CNAME

kramdown:
  input: GFM

title: Yosef Waysman
tagline: 'is a product guy'
url: http://yosef.me

author:
  name: Yosef Waysman
  email: yosefwaysman@gmail.com
