exclude:
- less
- Gemfile
- Gemfile.lock
- CNAME

kramdown:
  input: GFM

permalink: /:title

title: Yosef Waysman
tagline: 'is a product guy'
url: http://yosef.me

name: Yosef Waysman
email: yosefwaysman@gmail.com
