exclude:
- less
- Gemfile
- Gemfile.lock
- CNAME
- node_modules

kramdown:
  input: GFM

title: Yosef Waysman
tagline: 'UX/UI designer & coder'
url: http://yosefw.me

author:
  name: Yosef Waysman
  email: yosefwaysman@gmail.com
